BEShopDunk/Models/Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEShopDunk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int Id { get; set; }
        public string IDCate { get; set; }
        public string NameCate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}

BEShopDunk/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BEShopDunk.Models;
using System.Net;

namespace BEShopDunk.Controllers
{
    public class CategoriesController : Controller
    {
        // GET: Categories
        DBShopDunkEntities database = new DBShopDunkEntities();
        public ActionResult Index()
        {
            var categories = database.Categories.ToList();
            return View(categories);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Category category)
        {
            try
            {
                database.Categories.Add(category);
                database.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("LỖI TẠO MỚI CATEGORY");
            }
        }
        public ActionResult Details(int id)
        {
            var category = database.Categories.Where(c => c.Id == id).FirstOrDefault();
            return View(category);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var category=database.Categories.Where(c => c.Id == id).FirstOrDefault();
            return View(category);
        }
        [HttpPost]
        public ActionResult Edit(int id,Category category)
        {
            database.Entry(category).State = System.Data.Entity.EntityState.Modified;
            database.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var category = database.Categories.Where(c => c.Id == id).FirstOrDefault(); 
            if(category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                var category= database.Categories.Where(c => c.Id == id).FirstOrDefault();
                database.Categories.Remove(category);
                database.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("Không xóa được do liên quan tới bảng khác");
            }
        }
        public PartialViewResult CategoryPartial()
        {
            var cateList = database.Categories.ToList();
            return PartialView(cateList);
        }
    }
}

BEShopDunk/Controllers/CustomerProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BEShopDunk.Models;
using System.Net;
using System.Data.Entity;

namespace BEShopDunk.Controllers
{
    public class CustomerProductsController : Controller
    {
        // GET: CustomerProducts
        private DBShopDunkEntities db= new DBShopDunkEntities();
        public ActionResult Index(string category)
        {
            if (category == null)
            {
                var productList = db.Products.OrderByDescending(p => p.NamePro);
                return View(productList);
            }
            else
            {
                var products = db.Products.OrderByDescending(p => p.NamePro).Where(p => p.Category == category);
                return View(products.ToList());
            }
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
       public ActionResult SearchOption(double min=double.MinValue,double max = double.MaxValue)
        {
            var list=db.Products.Where(p=>(double)p.Price>=min && (double)p.Price<=max).ToList();
            return View(list);
        }
        public ActionResult PartialCate()
        {
            return PartialView();
        }
        public ActionResult SearchNameOption(string TenSp)
        {
            var list = db.Products.Where(p => p.NamePro == TenSp).ToList();
            return View(list);
        }
    }
}

BEShopDunk/Views/Categories/CategoryPartial.cshtml
@using BEShopDunk.Models
@model List<Category>
<style>
    #div-u {
       
        display:flex;
        background-color: #515154;
        text-decoration: none;
        margin:0;
        padding:0;
        gap:20px;
        width:fit-content;
    }

    .div-cate {
        height: fit-content;
        width: 100%;
    }

    a {
        color: white;
        text-decoration: none;
        font-size: x-large;
        padding:0;
        margin:0;
    }
    .div-cate:hover {
        background-color: #D3D3D3;
    }

        a:hover {
            text-decoration: none;
        }
</style>
<ul style="list-style-type:none" id="div-u">
    @{
        foreach (var item in Model)
        {
            <li class="div-cate">
                @Html.ActionLink(item.NameCate, "Index", "CustomerProducts", new { category = item.IDCate.Trim() }, "")
            </li>
            
        }
    }
</ul>

BEShopDunk/Views/Categories/Create.cshtml
@model BEShopDunk.Models.Category

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}

<h2>Create</h2>

<div style="margin: 10px auto; width: 70%;">
    <h2 style="text-align: center">TẠO MỚI CATEGORY</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class = "control-label col-md-2">MÃ CATEGORY</div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IDCate, new { htmlAttributes = new{ @class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.IDCate, "", new{ @class ="text-danger"})
                </div>

            </div>
            <div class="form-group">
                <div class="control-label col-md-2">TÊN CATEGORY</div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NameCate, new{ htmlAttributes = new{ @class = "form-control" }})
                    @Html.ValidationMessageFor(model => model.NameCate, "", new { @class= "text-danger"})
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10 mb-3 mt-3">
                    <input type="submit" value="TẠO MỚI" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }
    <div>
        @Html.ActionLink("TRỞ LẠI", "Index")
    </div>
</div>

BEShopDunk/Views/Categories/Delete.cshtml
@model BEShopDunk.Models.Category

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}


<div style="margin:10px auto;width:70%;">
    <h3 style="text-align:center">BẠN CÓ CHẮC CHẮN MUỐN XÓA CATEGORY NÀY</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
               MÃ CATEGORY
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IDCate)
            </dd>

            <dt>
               TÊN CATEGORY
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NameCate)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model=>model.Id)
            <div class="form-actions no-color">
                <input type="submit" value="Xóa" class="btn btn-danger" /> |
                @Html.ActionLink("Trở lại", "Index")
            </div>
        }
    </div>
</div>

BEShopDunk/Views/Categories/Details.cshtml
@model BEShopDunk.Models.Category

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}

<div style="margin:10px auto; width:70%">
    <h2 style="text-align:center">CHI TIẾT CATEGORY</h2>
    <div>
        <h4>THÔNG TIN CHI TIẾT</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                MÃ CATEGORY
            </dt>
            <dd>
                @Html.DisplayFor(model => model.IDCate)
            </dd>
            <dt>
                TÊN CATEGORY
            </dt>
            <dd>
                @Html.DisplayFor(model => model.NameCate)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-success" }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

BEShopDunk/Views/Categories/Edit.cshtml
@model BEShopDunk.Models.Category

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}


<div style="margin:10px;width:70%">
    <h2 style="text-align:center">CHỈNH SỬA CATEGORY</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Category</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                <div class="control-label col-md-2">MÃ CATEGORY</div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IDCate, new { htmlAttributes = new { @class = "form-control",@readonly="readonly" } })
                    @Html.ValidationMessageFor(model => model.IDCate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="control-label col-md-2">TÊN CATEGORY</div>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NameCate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NameCate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Lưu" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

BEShopDunk/Views/Categories/Index.cshtml
@model IEnumerable<BEShopDunk.Models.Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPageAdmin.cshtml";
}

<div style="margin: 10px auto; width: 70%;">
    <h2 style="text-align: center">THÔNG TIN CATEGORIES</h2>
    <p>
        @Html.ActionLink("TẠO MỚI", "Create", null, new{@class = "btn btn-primary"})
    </p>
    <table class="table">
        <tr>
            <th>
                MÃ CATEGORY
            </th>
            <th>
                TÊN CATEGORY
            </th>
            <th>
                LỆNH
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IDCate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NameCate)
                </td>
                <td>
                    @Html.ActionLink("Sửa", "Edit", new { id = item.Id }, new{@class = "btn btn-success"}) |
                    @Html.ActionLink("Chi tiết", "Details", new { id = item.Id }, new { @class = "btn btn-primary" }) |
                    @Html.ActionLink("Xóa", "Delete", new { id = item.Id }, new{@class = "btn btn-danger" })
                </td>
            </tr>
        }
    </table>
</div>